config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :recipes
  end
  # mount Fae below your admin namespec
  mount Fae::Engine => '/admin'

  root :to => 'pages#home'

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  include Fae::BaseModelConcern
  acts_as_list add_new_at: :top

  has_one :image, -> { where(attached_as: 'image') },
    as: :imageable,
    class_name: '::Fae::Image',
    dependent: :destroy
  accepts_nested_attributes_for :image, allow_destroy: true

  default_scope { order(:position) }

  def fae_display_field
    name
  end

end

app/controllers/admin/recipes_controller.rb
module Admin
  class RecipesController < Fae::BaseController

    private

    def build_assets
      @item.build_image if @item.image.blank?
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/fae/nav_items.rb
module Fae
  module NavItems
    extend ActiveSupport::Concern

    # returns an array of hashes to build navigation in Fae's application_controller
    #
    # - prefix application named routes with `main_app.`
    # - prefix Fae names routes with `fae.`
    # - do not include dashboard or admin nav items
    #
    # format:
    #   { text: 'Cities', path: main_app.admin_cities_path, class: 'if-you-want' },
    #     {
    #       text: 'Items with sublinks', sublinks: [
    #         { text: 'Item Sublink 1', path: main_app.admin_some_path },
    #         { text: 'Item Sublink 2', path: main_app.admin_someother_path }
    #       ]
    #     }
    #   },
    #   { text: 'Pages', path: fae.pages_path }
    def nav_items
      [
        { text: 'Recipes', path: main_app.admin_recipes_path },
        # scaffold inject marker
      ]
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/recipes/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  section.main_content-header
    .main_content-header-wrapper
      == render 'fae/shared/form_header', header: @klass_name
      == render 'fae/shared/form_buttons'
  == render 'fae/shared/errors'

  .main_content-sections
    section.main_content-section
      .main_content-section-area
        = fae_input f, :name
        = fae_input f, :yield
        = fae_input f, :prep_time
        = fae_input f, :cook_time
        = fae_input f, :description
        = fae_input f, :ingredients, markdown: true
        = fae_input f, :method, markdown: true
        = fae_input f, :possible_combination, markdown: true, label: 'Possible Combinations', helper_text: 'For how to use any potential waste.'
        = fae_image_form f, :image, show_alt: false

app/views/admin/recipes/edit.html.slim
== render 'form'

app/views/admin/recipes/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize

.main_content-sections
  section.main_content-section
    .main_content-section-area
      table.index_table.main_content-sortable
        thead
          tr
            th.main_content-sortable-handle-col
            th Name
            th Image
            th Yield
            th Prep Time
            th Cook Time
            th Modified
            th.main_table-header-delete data-sorter="false" Delete

        tbody
          - if @items.present?
            - @items.each do |item|
              tr id="#{@klass_singular}_#{item.id}"
                td.main_content-sortable-handle
                  span.icon-sort
                td.main_table-description-item
                  = link_to item.fae_display_field, edit_admin_recipe_path(item)
                td = image_tag(item.image.asset.thumb.url) if item.image.present?
                td = item.yield
                td = item.prep_time
                td = item.cook_time
                td = fae_date_format item.updated_at
                td.main_table-delete
                  = link_to ['admin', item], method: :delete, data: { confirm: t('fae.delete_confirmation') }, class: 'main_table-action' do
                    span.icon-delete_x
          - else
            tr
              td colspan="8" No items found

app/views/admin/recipes/new.html.slim
== render 'form'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Boh</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>